4) 
To perform label encoding using Python's scikit-learn library, you can use the LabelEncoder class from the sklearn.preprocessing module. Here's the code to label encode the categorical variables in your dataset.

In [1]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

# Create a sample dataset
data = {
    'Color': ['red', 'green', 'blue', 'red', 'blue'],
    'Size': ['small', 'medium', 'large', 'small', 'medium'],
    'Material': ['wood', 'metal', 'plastic', 'wood', 'metal']
}

# Convert the dataset to a DataFrame
df = pd.DataFrame(data)

# Create a LabelEncoder instance
label_encoder = LabelEncoder()

# Iterate over each column in the DataFrame
for column in df.columns:
    # Label encode the values in the column
    df[column] = label_encoder.fit_transform(df[column])

# Print the encoded DataFrame
print(df)

   Color  Size  Material
0      2     2         2
1      1     1         0
2      0     0         1
3      2     2         2
4      0     1         0


5) 

In [2]:

import numpy as np

# Create a sample dataset
data = np.array([
    [25, 50000, 12],
    [30, 60000, 16],
    [35, 70000, 14],
    [40, 80000, 18],
    [45, 90000, 20]
])

# Calculate the covariance matrix
cov_matrix = np.cov(data, rowvar=False)

# Print the covariance matrix
print(cov_matrix)

[[6.25e+01 1.25e+05 2.25e+01]
 [1.25e+05 2.50e+08 4.50e+04]
 [2.25e+01 4.50e+04 1.00e+01]]
